### ISSUE TITLE
Exception 'Cannot access a disposed object.'

### ISSUE THREAD

**Issue by danez** [zawawawa/GatelessGateSharp#52]
I just had the following in my log.

```
2018-02-14 15:51:19.7237 [17] Exception in Stratum.StreamReaderThread(): System.Exception: Stratum server sent duplicate job.
   at GatelessGateSharp.OpenEthereumPoolEthashStratum.ProcessLine(String line)
   at GatelessGateSharp.Stratum.StreamReaderThread()
2018-02-14 15:51:19.9893 [4] Exception in ping thread: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at GatelessGateSharp.Stratum.WriteLine(String line)
   at GatelessGateSharp.OpenEthereumPoolEthashStratum.PingThread()
2018-02-14 15:51:20.2081 [1] Stopping miners...
2018-02-14 15:51:20.7081 [1] Stopped miners.
2018-02-14 15:51:21.5520 [1] Saving settings to C:\Users\user\AppData\Roaming\GatelessGateSharp\GatelessGateSharp.sqlite...
2018-02-14 15:51:25.0055 [25] Exception in ping thread: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at GatelessGateSharp.Stratum.WriteLine(String line)
   at GatelessGateSharp.OpenEthereumPoolEthashStratum.PingThread()
2018-02-14 15:51:25.8181 [1] Saved settings.
2018-02-14 15:51:25.8337 [1] Saving settings to C:\Users\user\AppData\Roaming\GatelessGateSharp\Backups\2018-02-14--1551.sqlite...
2018-02-14 15:51:30.0060 [1] Saved settings.
2018-02-14 15:51:30.0529 [1] Launching Ethash miners for DwarfPool...
```

The miner recovered, but I just wondered why it had to stop mining and restart and if this is intentional.

**Comment by zawawawa** [comment]
IIRC, it is necessary to restart mining for some pools. Pretty weird, I know...
