### ISSUE TITLE
command line not working since 1.2.11 alpha

### ISSUE THREAD

**Issue by Fedeparma74** [zawawawa/GatelessGateSharp#53]
2018-02-15 14:45:22.7061 [1] Gateless Gate Sharp 1.2.10 alpha started.
2018-02-15 14:45:23.2641 [1] Number of Devices: 1
2018-02-15 14:45:23.2801 [1] Successfully initialized AMD Display Library.
2018-02-15 14:45:23.2801 [1] Number of ADL Adapters: 16
2018-02-15 14:45:23.2872 [1] Failed to initialize NVIDIA Management Library.
2018-02-15 14:45:23.3363 [1] Exception in InitializeDevices(): Object reference not set to an instance of an object.   at GatelessGateSharp.MainForm.ResetDeviceAlgorithmSettings(Device device)
   at GatelessGateSharp.MainForm.ResetDeviceSettings(Device device)
   at GatelessGateSharp.MainForm.InitializeDevices()
   at GatelessGateSharp.MainForm.MainForm_Load(Object sender, EventArgs e)
2018-02-15 14:45:23.3398 [1] Invalid argument: C:\Users\fedep\Desktop\Gateless Gate Sharp\GatelessGateSharpCL.exe
2018-02-15 14:45:23.3563 [4] Hardware management task started.
2018-02-15 14:45:23.4696 [1] Launching miner(s) for Custom Pool 0...
2018-02-15 14:45:23.6561 [1] Failed to launch miner(s) for Custom Pool 0: Object reference not set to an instance of an object.   at GatelessGateSharp.MainForm.LaunchOpenCLNeoScryptMinersWithStratum(NeoScryptStratum stratum)
   at GatelessGateSharp.MainForm.LaunchMinersForCustomPool(String algo, String host, Int32 port, String login, String password, String algo2, String host2, Int32 port2, String login2, String password2)
   at GatelessGateSharp.MainForm.LaunchMinersForCustomPools()
2018-02-15 14:45:23.6582 [1] Stopping miners...
2018-02-15 14:45:23.6602 [9] Difficulty set to 4096.
2018-02-15 14:45:23.6602 [9] Received new job: 00000017154ce6da
2018-02-15 14:45:25.8871 [9] Received new job: 00000017154cf07c
2018-02-15 14:45:26.3554 [12] Running garbage collection...
2018-02-15 14:45:26.3554 [12] Memory used before collection: 15MB
2018-02-15 14:45:28.7077 [12] Memory used before collection: 10MB
2018-02-15 14:45:28.7077 [1] Stopped miners.

**Comment by zawawawa** [comment]
I will look into it.

**Comment by zawawawa** [comment]
Sorry about the delay... I will work on another command-line version after v1.3.6.
