### ISSUE TITLE
Settings aren't saving on closing. Optimzation doesn't work. Miner broken?

### ISSUE THREAD

**Issue by Isuress** [zawawawa/GatelessGateSharp#65]
I am unable to use Gateless Gat Sharp on one of my miners.
I haven't yet had issues with another miner but this one has been giving me issues for some reason.

Installed using .msi, running as administrator, allowed page pool recommended increase, do settings, run optimize or try to mine, everything breaks.

Log file outputs this:
```
2018-04-09 14:43:18.9576 [1] Gateless Gate Sharp 1.3.2 prealpha started.
2018-04-09 14:43:21.0700 [1] Number of Devices: 1
2018-04-09 14:43:21.1042 [1] Successfully initialized AMD Display Library.
2018-04-09 14:43:21.1042 [1] Number of ADL Adapters: 9
2018-04-09 14:43:21.1119 [1] ADL_Adapter_AdapterInfo_Get() returned error code 0
2018-04-09 14:43:21.1139 [1] Failed to initialize NVIDIA Management Library.
2018-04-09 14:43:21.1219 [1] Exception in UpdateControls(): The given key was not present in the dictionary.   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at GatelessGateSharp.MainForm.UpdateControls()
2018-04-09 14:43:22.2689 [1] Loading settings from C:\Users\miner\AppData\Roaming\GatelessGateSharp\GatelessGateSharp.sqlite...
2018-04-09 14:43:22.3758 [1] Exception: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
2018-04-09 14:43:22.3758 [1]     Member:      LoadSettingsFromDatabase
2018-04-09 14:43:22.3758 [1]     Source File: D:\GitHub\GatelessGateSharp\GatelessGateSharp\MainForm.cs
2018-04-09 14:43:22.3758 [1]     Line Number: 819
2018-04-09 14:43:22.3758 [1]     StackTrace:     at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.Initialize()
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at GatelessGateSharp.MainForm.LoadSettingsFromDatabase(String filePath)
2018-04-09 14:43:22.3848 [1] Invalid argument: C:\Program Files\Zawawa Software LLC\Gateless Gate Sharp\GatelessGateSharp.exe
2018-04-09 14:43:26.6203 [13] Running garbage collection...
2018-04-09 14:43:26.6203 [13] Memory used before collection: 18MB
2018-04-09 14:43:27.0717 [13] Memory used before collection: 10MB
2018-04-09 14:43:33.8157 [15] API Listener started.
```

- Same error is reported on v1.3.0; which is why I upgraded to v1.3.2.
- I can confirm that _"SQLite.Interop.dll"_ are correctly installed in the x86 and x64 folders of the program's directory.
- .zip installation gives the same issue.
- Issue persists after OS restart.

**Comment by Isuress** [comment]
Good luck man! No problem.

Any ideas on how to fix this though? Maybe a work around? I'm using Gateless on a handful of machines; there's just the odd one that gets this issue for an inexplicable reason.

**Comment by zawawawa** [comment]
Starting at v1.3.6, the default format for the global configuration file will be JSON. Thanks again for the report!

**Comment by Isuress** [comment]
Thanks, my dude!
